###############################################################################
# proj3/01_run_sim.R
#
# Run the specmutual simulation for ONE parameter combination.
# Called by the SLURM array job; each array task runs this script with a
# different combo_id.
#
# Usage:
#   Rscript proj3/01_run_sim.R <combo_id>
#
# Reads:  proj3/param_table.csv   (generated by 00_generate_params.R)
#         script/M0.RData          (mainland interaction matrix)
# Writes: proj3/results/combo_<NNN>.rds
###############################################################################

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 1) stop("Usage: Rscript 01_run_sim.R <combo_id>")
combo_id <- as.numeric(args[1])

library(specmutual)

# ---------------------------------------------------------------------------
# Paths — adjust the base path for your cluster home directory
# On the cluster the repo is typically at ~/specmutual/
# ---------------------------------------------------------------------------
base_dir  <- "~/specmutual"

# param_csv <- file.path(base_dir, "proj3", "param_table.csv")
param_csv <- file.path(base_dir, "proj3", "param_table_Nomutual.csv") # use this to explore
# no mutualism effect scenarios

m0_path   <- file.path(base_dir, "script", "M0.RData")
out_dir   <- file.path(base_dir, "proj3", "results_Nomutual")

# ---------------------------------------------------------------------------
# Load inputs
# ---------------------------------------------------------------------------
load(m0_path)  # loads object `M0`

params <- read.csv(param_csv)
p <- params[params$combo_id == combo_id, ]
if (nrow(p) != 1) stop("combo_id ", combo_id, " not found in param_table.csv")

cat("=== proj3: combo", combo_id, "===\n")
cat("Parameters:\n")
print(as.data.frame(p))

# ---------------------------------------------------------------------------
# Build mutualism_pars (symmetric for plants and animals)
# ---------------------------------------------------------------------------
mutualism_pars <- specmutual::create_mutual_pars(
  lac_pars  = c(p$lac_0, p$lac_0),
  mu_pars   = c(p$mu_0,  p$mu_0,  p$mu_1,  p$mu_1),
  K_pars    = c(p$K_0,   p$K_0,   p$K_1,   p$K_1),
  gam_pars  = c(p$gam_0, p$gam_0),
  laa_pars  = c(p$laa_0, p$laa_0, p$laa_1, p$laa_1),
  qgain     = 0.001,
  qloss     = 0.001,
  lambda0   = p$lambda0,
  M0        = M0,
  transprob = 1.0,
  alpha     = 100
)

# ---------------------------------------------------------------------------
# Simulation settings
# ---------------------------------------------------------------------------
n_reps       <- 5       # replicates per combination
total_time   <- 10      # island age in MY (same as manuscript)
max_attempts <- 100     # max Gillespie attempts per replicate (safety net)

# Reproducible seed based on combo_id
set.seed(combo_id * 17 + 3)

# ---------------------------------------------------------------------------
# Safe wrapper around sim_core_mutualism
# Mirrors peregrine_sim but with a max-attempt cap so the job does not hang
# on difficult parameter combos.
# ---------------------------------------------------------------------------
safe_sim <- function(total_time, n_reps, mutualism_pars, max_attempts) {
  island_replicates <- list()
  tried <- 0
  i     <- 1

  while (i <= n_reps && tried < max_attempts) {
    tried <- tried + 1

    sim_output <- tryCatch(
      specmutual::sim_core_mutualism(
        total_time     = total_time,
        mutualism_pars = mutualism_pars,
        return_parts   = "island_parts"
      ),
      error = function(e) {
        message("  Error in attempt ", tried, ": ", conditionMessage(e))
        NULL
      }
    )

    if (is.null(sim_output)) next

    # Keep only replicates with at least a 2x2 island network
    Mt       <- sim_output$Mt
    status_p <- sim_output$status_p
    status_a <- sim_output$status_a
    true_Mt  <- Mt[status_p == 1, status_a == 1, drop = FALSE]

    if (nrow(true_Mt) >= 2 && ncol(true_Mt) >= 2) {
      island_replicates[[i]] <- sim_output
      cat("  Replicate", i, "done (attempt", tried, ")\n")
      i <- i + 1
    } else {
      message("  Attempt ", tried, " dropped: network < 2x2")
    }
  }

  if (tried >= max_attempts && i <= n_reps) {
    warning("Max attempts (", max_attempts, ") reached. Only ",
            length(island_replicates), " of ", n_reps, " replicates completed.")
  }
  return(island_replicates)
}

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------
cat("\nStarting simulation at", format(Sys.time()), "\n")
t_start <- proc.time()

sim_output <- safe_sim(
  total_time     = total_time,
  n_reps         = n_reps,
  mutualism_pars = mutualism_pars,
  max_attempts   = max_attempts
)

elapsed <- (proc.time() - t_start)["elapsed"]
cat("\nFinished at", format(Sys.time()), "- elapsed:", round(elapsed / 60, 1), "min\n")
cat("Successful replicates:", length(sim_output), "/", n_reps, "\n")

# ---------------------------------------------------------------------------
# Save result
# ---------------------------------------------------------------------------
if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)

result <- list(
  combo_id   = combo_id,
  params     = as.list(p),
  n_reps_ok  = length(sim_output),
  elapsed_s  = as.numeric(elapsed),
  sim_output = sim_output
)

# outfile <- file.path(out_dir, sprintf("combo_%03d.rds", combo_id))
# alternative use
outfile <- file.path(out_dir, sprintf("Nomutual_combo_%03d.rds", combo_id))

saveRDS(result, file = outfile)
cat("Saved to", outfile, "\n")
