###############################################################################
#
# Run the specmutual simulation for ONE parameter combination.
# Called by the SLURM array job; each array task runs this script with a
# different combo_id.
#
# Usage:
#   Rscript proj3/part2_newSim/01_run_sim.R <combo_id>
#
# Reads:  proj3/part2_newSim/param_table.csv   (generated by 00_generate_params.R)
#         script/M0.RData          (mainland interaction matrix)
# Writes: proj3/part2_newSim/results/combo_<NNN>.rds
#         proj3/part2_newSim/checkpoints/combo_<NNN>.partial.rds while running
###############################################################################

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 1) stop("Usage: Rscript 01_run_sim.R <combo_id>")
combo_id <- as.numeric(args[1])
if (is.na(combo_id) || combo_id != as.integer(combo_id)) {
  stop("combo_id must be an integer")
}
combo_id <- as.integer(combo_id)

base_dir <- "~/specmutual"
base_dir <- path.expand(base_dir)

param_csv <- file.path(base_dir, "proj3", "part2_newSim", "param_table.csv")
# param_csv <- file.path(base_dir, "proj3", "param_table_Nomutual.csv") # use this to explore
# no mutualism effect scenarios

m0_path   <- file.path(base_dir, "script", "M0.RData")
run_dir   <- file.path(base_dir, "proj3", "part2_newSim")
out_dir   <- file.path(run_dir, "results")
ckpt_dir  <- file.path(run_dir, "checkpoints")
status_dir <- file.path(run_dir, "status")
# out_dir   <- file.path(base_dir, "proj3", "results_Nomutual")

# ---------------------------------------------------------------------------
# Simulation settings
# ---------------------------------------------------------------------------
n_reps       <- 10       # replicates per combination
total_time   <- 10       # island age in MY (same as manuscript)
max_attempts <- 100      # max Gillespie attempts per job attempt

combo_tag <- sprintf("combo_%03d", combo_id)
outfile   <- file.path(out_dir, paste0(combo_tag, ".rds"))
ckpt_file <- file.path(ckpt_dir, paste0(combo_tag, ".partial.rds"))
running_file <- file.path(status_dir, paste0(combo_tag, ".running"))
complete_file <- file.path(status_dir, paste0(combo_tag, ".complete"))
failed_file <- file.path(status_dir, paste0(combo_tag, ".failed"))

dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(ckpt_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(status_dir, recursive = TRUE, showWarnings = FALSE)

save_rds_atomic <- function(object, file) {
  tmp <- paste0(file, ".tmp.", Sys.getpid())
  saveRDS(object, file = tmp)
  if (!file.rename(tmp, file)) {
    unlink(tmp)
    stop("Could not move temporary file into place: ", file)
  }
}

mark_status <- function(path, text) {
  writeLines(text, con = path)
}

# Skip only truly complete outputs. Older incomplete outputs can be resumed.
if (file.exists(outfile)) {
  existing <- tryCatch(readRDS(outfile), error = function(e) NULL)
  if (!is.null(existing) &&
      isTRUE(existing$n_reps_ok >= n_reps) &&
      length(existing$sim_output) >= n_reps) {
    cat("Combo", combo_id, "already complete at", outfile, "- skipping.\n")
    mark_status(complete_file, paste("complete", Sys.time()))
    unlink(c(running_file, failed_file))
    quit(save = "no", status = 0)
  }
  cat("Found incomplete or unreadable result for", combo_tag, "- will resume/retry.\n")
}

mark_status(running_file, paste("running", Sys.time()))
unlink(failed_file)

library(specmutual)

# ---------------------------------------------------------------------------
# Load inputs
# ---------------------------------------------------------------------------
load(m0_path)  # loads object `M0`

params <- read.csv(param_csv)
p <- params[params$combo_id == combo_id, ]
if (nrow(p) != 1) stop("combo_id ", combo_id, " not found in param_table.csv")

cat("=== proj3: combo", combo_id, "===\n")
cat("Parameters:\n")
print(as.data.frame(p))

# ---------------------------------------------------------------------------
# Build mutualism_pars (symmetric for plants and animals)
# ---------------------------------------------------------------------------
mutualism_pars <- specmutual::create_mutual_pars(
  lac_pars  = c(p$lac_0, p$lac_0),
  mu_pars   = c(p$mu_0,  p$mu_0,  p$mu_1,  p$mu_1),
  K_pars    = c(p$K_0,   p$K_0,   p$K_1,   p$K_1),
  gam_pars  = c(p$gam_0, p$gam_0),
  laa_pars  = c(p$laa_0, p$laa_0, p$laa_1, p$laa_1),
  qgain     = 0.001,
  qloss     = 0.001,
  lambda0   = p$lambda0,
  M0        = M0,
  transprob = 1.0,
  alpha     = 100
)

# Reproducible seed based on combo_id
set.seed(combo_id * 17 + 3)

# ---------------------------------------------------------------------------
# Safe wrapper around sim_core_mutualism
# Mirrors peregrine_sim but with a max-attempt cap so the job does not hang
# on difficult parameter combos. Accepted replicates are checkpointed so a
# killed or timed-out Slurm task can continue where it stopped.
# ---------------------------------------------------------------------------
load_checkpoint <- function() {
  for (path in c(ckpt_file, outfile)) {
    if (!file.exists(path)) next
    obj <- tryCatch(readRDS(path), error = function(e) NULL)
    if (!is.null(obj) && is.list(obj$sim_output)) {
      cat("Loaded checkpoint/result from", path, "with",
          length(obj$sim_output), "replicates.\n")
      return(obj$sim_output)
    }
  }
  list()
}

checkpoint_result <- function(island_replicates, elapsed = NA_real_) {
  result <- list(
    combo_id   = combo_id,
    params     = as.list(p),
    n_reps_ok  = length(island_replicates),
    target_reps = n_reps,
    elapsed_s  = as.numeric(elapsed),
    updated_at = as.character(Sys.time()),
    complete   = length(island_replicates) >= n_reps,
    sim_output = island_replicates
  )
  save_rds_atomic(result, ckpt_file)
}

safe_sim <- function(total_time, n_reps, mutualism_pars, max_attempts,
                     island_replicates = list()) {
  tried <- 0
  i     <- length(island_replicates) + 1

  if (i <= n_reps) {
    cat("Resuming at replicate", i, "of", n_reps, "\n")
  }

  while (i <= n_reps && tried < max_attempts) {
    tried <- tried + 1

    sim_output <- tryCatch(
      specmutual::sim_core_mutualism(
        total_time     = total_time,
        mutualism_pars = mutualism_pars,
        return_parts   = "island_parts"
      ),
      error = function(e) {
        message("  Error in attempt ", tried, ": ", conditionMessage(e))
        NULL
      }
    )

    if (is.null(sim_output)) next

    # Keep only replicates with at least a 2x2 island network
    Mt       <- sim_output$Mt
    status_p <- sim_output$status_p
    status_a <- sim_output$status_a
    true_Mt  <- Mt[status_p == 1, status_a == 1, drop = FALSE]

    if (nrow(true_Mt) >= 2 && ncol(true_Mt) >= 2) {
      island_replicates[[i]] <- sim_output
      cat("  Replicate", i, "done (attempt", tried, ")\n")
      checkpoint_result(island_replicates)
      i <- i + 1
    } else {
      message("  Attempt ", tried, " dropped: network < 2x2")
    }
  }

  if (tried >= max_attempts && i <= n_reps) {
    warning("Max attempts (", max_attempts, ") reached. Only ",
            length(island_replicates), " of ", n_reps, " replicates completed.")
  }
  island_replicates
}

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------
cat("\nStarting simulation at", format(Sys.time()), "\n")
t_start <- proc.time()

existing_replicates <- load_checkpoint()
sim_output <- safe_sim(
  total_time     = total_time,
  n_reps         = n_reps,
  mutualism_pars = mutualism_pars,
  max_attempts   = max_attempts,
  island_replicates = existing_replicates
)

elapsed <- (proc.time() - t_start)["elapsed"]
cat("\nFinished at", format(Sys.time()), "- elapsed:", round(elapsed / 60, 1), "min\n")
cat("Successful replicates:", length(sim_output), "/", n_reps, "\n")

# ---------------------------------------------------------------------------
# Save result
# ---------------------------------------------------------------------------
result <- list(
  combo_id   = combo_id,
  params     = as.list(p),
  n_reps_ok  = length(sim_output),
  target_reps = n_reps,
  elapsed_s  = as.numeric(elapsed),
  updated_at = as.character(Sys.time()),
  complete   = length(sim_output) >= n_reps,
  sim_output = sim_output
)

# alternative use
# outfile <- file.path(out_dir, sprintf("Nomutual_combo_%03d.rds", combo_id))

if (length(sim_output) >= n_reps) {
  save_rds_atomic(result, outfile)
  mark_status(complete_file, paste("complete", Sys.time()))
  unlink(c(ckpt_file, running_file, failed_file))
  cat("Saved complete result to", outfile, "\n")
  quit(save = "no", status = 0)
}

checkpoint_result(sim_output, elapsed = elapsed)
mark_status(
  failed_file,
  paste("incomplete", Sys.time(), "n_reps_ok", length(sim_output), "target", n_reps)
)
unlink(running_file)
cat("Saved incomplete checkpoint to", ckpt_file, "\n")
quit(save = "no", status = 2)
